export const ERROR_CODES = {
  INVALID_REQUEST: "INVALID_REQUEST",
  UNSUPPORTED_ACTION: "UNSUPPORTED_ACTION",
  UNSUPPORTED_SELECTION_KIND: "UNSUPPORTED_SELECTION_KIND",
  MIXED_SELECTION_UNSUPPORTED: "MIXED_SELECTION_UNSUPPORTED",
  PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
  FILE_ACCESS_FAILED: "FILE_ACCESS_FAILED",
  PROMPT_REQUIRED: "PROMPT_REQUIRED",
  OPENCLAW_UNAVAILABLE: "OPENCLAW_UNAVAILABLE",
  OPENCLAW_TIMEOUT: "OPENCLAW_TIMEOUT",
  SESSION_CREATE_FAILED: "SESSION_CREATE_FAILED",
  MESSAGE_SEND_FAILED: "MESSAGE_SEND_FAILED",
  GENERATION_FAILED: "GENERATION_FAILED",
  STREAMING_UNAVAILABLE: "STREAMING_UNAVAILABLE",
  SCREENSHOT_CAPTURE_FAILED: "SCREENSHOT_CAPTURE_FAILED",
  WEBUI_OPEN_FAILED: "WEBUI_OPEN_FAILED",
  POPUP_RENDER_FAILED: "POPUP_RENDER_FAILED",
  REWRITE_APPLY_FAILED: "REWRITE_APPLY_FAILED",
  CLIPBOARD_WRITE_FAILED: "CLIPBOARD_WRITE_FAILED",
  UNAUTHORIZED_ORIGIN: "UNAUTHORIZED_ORIGIN",
  INVALID_LOCAL_TOKEN: "INVALID_LOCAL_TOKEN",
  BACKEND_SETUP_REQUIRED: "BACKEND_SETUP_REQUIRED",
  BACKEND_UNAVAILABLE: "BACKEND_UNAVAILABLE",
  BACKEND_UNSUPPORTED_ACTION: "BACKEND_UNSUPPORTED_ACTION"
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
